### ISSUE TITLE
Add a signup button

### ISSUE THREAD

**Issue by djspiewak** [djspiewak/issue-testing#11]
- [ ] Edit the HTML
- [ ] Install Rails
  + [ ] Be annoyed that we're using Rails
  + [ ] Shave some yaks investigating alternate technologies
- [ ] Wire up the button logic
- [ ] …
- [ ] Profit
